export enum ErrorCode {
    StudioNotFound = 'Studio not found',
    Unauthorized = 'Unauthorized',
    AppointmentNotFound = 'Appointment not found',
    BookingLimitExceeded = 'You can only book 10 appointments per 12 hours',
    ShiftNotFound = 'Shift not found',
    ShiftFull = 'Shift is full',
    DuplicateAppointment = 'You have already booked appointment at this time',
    ServiceNotFound = 'Service not found',
    ServiceNotFoundInStudio = 'Service not found in the studio',
    SomethingWentWrong = 'Something went wrong',
    ArtistNotAvailable = 'Artist is not available at this time',
    CannotRescheduleAppointment = 'Appointment cannot be rescheduled',
    AppointmentAlreadyCanceled = 'Appointment already canceled',
    AppointmentAlreadyCompleted = 'Appointment already completed',
    AppointmentAlreadyLate = 'Appointment already late',
    CannotCancelAppointment = 'Appointment cannot be canceled',
    NoPermissionToViewAppointment = 'You are not allowed to view this appointment',
    NoPermissionToUpdateAppointment = 'You are not allowed to update this appointment',
    CannotUpdateAppointment = 'Appointment cannot be updated',
    UserNotFound = 'User not found',
    WrongPassword = 'Wrong password',
    EmailAlreadyExists = 'Email already exists',
    InvalidCode = 'Invalid code',
    CreateFailed = 'Create failed',
    CategoryNotFound = 'Category not found',
    NoPermissionToViewInvoice = "You don't have permission to view this invoice",
    InvoiceNotFound = 'Invoice not found',
    CanOnlyCreateInvoicesForConfirmedAppointments = 'You can only create invoices for confirmed appointments',
    CreateInvoiceFailed = 'Create invoice failed',
    FileEmpty = 'File is empty',
    NotImageFileType = 'File is not an image type (jpg, png, gif, webp)',
    FileTooLarge5MB = 'File is too large, max size is 5MB',
    FileTooLarge20MB = 'File is too large, max size is 20MB',
    NotCertificateFileType = 'File is not a certificate type (pdf, doc, docx)',
    InvalidFileType = 'File type is invalid',
    ErrorUploadingFile = 'Error uploading file',
    EndDateGreaterThanStartDate = 'End date must be greater than start date',
    NoPermissionToAccessStudio = "You don't have permission to access this studio",
    StudioNoWorkingTime = 'Studio has no working time',
    StudioNotFoundAgain = 'Studio Not found',
    StudioCreateFail = 'Studio Create Fail',
    ActivateStudioFailed = 'Activate studio failed',
    UpdateStudioFailed = 'Update studio failed',
    DeleteStudioFailed = 'Delete studio failed',
    StudioArtistsNotFound = 'Studio Artists Not found',
    StudioUsersNotFound = 'Studio Users Not found',
    StudioUserExists = 'Studio User Exists',
    StudioUserCreateFail = 'Studio User Create Fail',
    InvalidRequest = 'Invalid request',
    UpdateStudioUserFailed = 'Update studio user failed',
    StudioUserNotFound = 'Studio User Not found',
    DeleteStudioUserFailed = 'Delete studio user failed',
    StudioServiceNotFound = 'Studio Service not found',
    CouldNotFindCategory = 'Could not find Category',
    DeleteFailed = 'Delete failed',
    UpdateStudioServiceFailed = 'Update Studio Service failed',
    TestimonialNotFound = 'Testimonial not found',
    Forbidden = "Forbidden, you don't have permission",
    CreateUserFailed = 'Create user failed',
    UpdateUserFailed = 'Update user failed',
    UpdatePasswordFailed = 'Update password failed',
    NoTokenProvided = 'No token provided',
    PermissionDenied = 'Permission denied',
}

export const errorMsg: Record<ErrorCode, string> = {
    [ErrorCode.StudioNotFound]: 'Không tìm thấy studio',
    [ErrorCode.Unauthorized]: 'Không được ủy quyền',
    [ErrorCode.AppointmentNotFound]: 'Không tìm thấy cuộc hẹn',
    [ErrorCode.BookingLimitExceeded]: 'Bạn chỉ có thể đặt 10 cuộc hẹn trong 12 giờ',
    [ErrorCode.ShiftNotFound]: 'Không tìm thấy ca làm việc',
    [ErrorCode.ShiftFull]: 'Ca làm việc đã đầy',
    [ErrorCode.DuplicateAppointment]: 'Bạn đã đặt cuộc hẹn vào thời điểm này',
    [ErrorCode.ServiceNotFound]: 'Dịch vụ không được tìm thấy',
    [ErrorCode.ServiceNotFoundInStudio]: 'Không tìm thấy dịch vụ trong studio',
    [ErrorCode.SomethingWentWrong]: 'Có lỗi xảy ra',
    [ErrorCode.ArtistNotAvailable]: 'Nghệ sĩ không khả dụng vào thời điểm này',
    [ErrorCode.CannotRescheduleAppointment]: 'Không thể đặt lại cuộc hẹn',
    [ErrorCode.AppointmentAlreadyCanceled]: 'Cuộc hẹn đã bị hủy',
    [ErrorCode.AppointmentAlreadyCompleted]: 'Cuộc hẹn đã hoàn thành',
    [ErrorCode.AppointmentAlreadyLate]: 'Cuộc hẹn đã quá hạn',
    [ErrorCode.CannotCancelAppointment]: 'Không thể hủy cuộc hẹn',
    [ErrorCode.NoPermissionToViewAppointment]: 'Bạn không được phép xem cuộc hẹn này',
    [ErrorCode.NoPermissionToUpdateAppointment]: 'Bạn không được phép cập nhật cuộc hẹn này',
    [ErrorCode.CannotUpdateAppointment]: 'Không thể cập nhật cuộc hẹn',
    [ErrorCode.UserNotFound]: 'Người dùng không được tìm thấy',
    [ErrorCode.WrongPassword]: 'Mật khẩu sai',
    [ErrorCode.EmailAlreadyExists]: 'Email đã tồn tại',
    [ErrorCode.InvalidCode]: 'Mã không hợp lệ',
    [ErrorCode.CreateFailed]: 'Tạo không thành công',
    [ErrorCode.CategoryNotFound]: 'Không tìm thấy danh mục',
    [ErrorCode.NoPermissionToViewInvoice]: 'Bạn không có quyền xem hóa đơn này',
    [ErrorCode.InvoiceNotFound]: 'Không tìm thấy hóa đơn',
    [ErrorCode.CanOnlyCreateInvoicesForConfirmedAppointments]: 'Bạn chỉ có thể tạo hóa đơn cho cuộc hẹn đã xác nhận',
    [ErrorCode.CreateInvoiceFailed]: 'Tạo hóa đơn không thành công',
    [ErrorCode.FileEmpty]: 'Tệp trống rỗng',
    [ErrorCode.NotImageFileType]: 'Tệp không phải là loại hình ảnh (jpg, png, gif, webp)',
    [ErrorCode.FileTooLarge5MB]: 'Tệp quá lớn, dung lượng tối đa là 5MB',
    [ErrorCode.FileTooLarge20MB]: 'Tệp quá lớn, dung lượng tối đa là 20MB',
    [ErrorCode.NotCertificateFileType]: 'Tệp không phải là loại chứng chỉ (pdf, doc, docx)',
    [ErrorCode.InvalidFileType]: 'Loại tệp không hợp lệ',
    [ErrorCode.ErrorUploadingFile]: 'Lỗi khi tải',
    [ErrorCode.EndDateGreaterThanStartDate]: 'Ngày kết thúc phải lớn hơn ngày bắt đầu',
    [ErrorCode.NoPermissionToAccessStudio]: 'Bạn không có quyền truy cập studio này',
    [ErrorCode.StudioNoWorkingTime]: 'studio không có thời gian làm việc',
    [ErrorCode.StudioNotFoundAgain]: 'Không tìm thấy studio',
    [ErrorCode.StudioCreateFail]: 'Tạo studio không thành công',
    [ErrorCode.ActivateStudioFailed]: 'Kích hoạt studio không thành công',
    [ErrorCode.UpdateStudioFailed]: 'Cập nhật studio không thành công',
    [ErrorCode.DeleteStudioFailed]: 'Xóa studio không thành công',
    [ErrorCode.StudioArtistsNotFound]: 'Không tìm thấy nghệ sĩ trong studio',
    [ErrorCode.StudioUsersNotFound]: 'Không tìm thấy người dùng trong studio',
    [ErrorCode.StudioUserExists]: 'Người dùng trong studio đã tồn tại',
    [ErrorCode.StudioUserCreateFail]: 'Tạo người dùng trong studio không thành công',
    [ErrorCode.InvalidRequest]: 'Yêu cầu không hợp lệ',
    [ErrorCode.UpdateStudioUserFailed]: 'Cập nhật người dùng trong studio không thành công',
    [ErrorCode.StudioUserNotFound]: 'Không tìm thấy người dùng trong studio',
    [ErrorCode.DeleteStudioUserFailed]: 'Xóa người dùng trong studio không thành công',
    [ErrorCode.StudioServiceNotFound]: 'Không tìm thấy dịch vụ trong studio',
    [ErrorCode.CouldNotFindCategory]: 'Không thể tìm thấy danh mục',
    [ErrorCode.DeleteFailed]: 'Xóa không thành công',
    [ErrorCode.UpdateStudioServiceFailed]: 'Cập nhật dịch vụ trong studio không thành công',
    [ErrorCode.TestimonialNotFound]: 'Không tìm thấy đánh giá',
    [ErrorCode.Forbidden]: 'Bị cấm, bạn không có quyền',
    [ErrorCode.CreateUserFailed]: 'Tạo người dùng không thành công',
    [ErrorCode.UpdateUserFailed]: 'Cập nhật người dùng không thành công',
    [ErrorCode.UpdatePasswordFailed]: 'Cập nhật mật khẩu không thành công',
    [ErrorCode.NoTokenProvided]: 'Không có mã thông tin nào được cung cấp',
    [ErrorCode.PermissionDenied]: 'Từ chối quyền',
};

errorMsg[ErrorCode.StudioUsersNotFound];
